server:
  port: 8090
spring:
  cloud:
    config:
      server:
        git:
          default-label: multiple-instances
          uri: https://github.com/mnolascoc/gestion-vehiculos-microservices.git
          search-paths: config-data
  application:
    name: config-service